openapi: 3.0.0
info:
  title: Heating Control Service
  version: 1.0.0
paths:
  /heating/on:
    post:
      summary: Включить отопление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                temperature:
                  type: number
      responses:
        '200':
          description: Heating turned on
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /heating/off:
    post:
      summary: Выключить отопление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Heating turned off
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /heating/status:
    get:
      summary: Получить статус отопления
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current heating status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  temperature:
                    type: number
